[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "alembic>=1.18.5",
    "fastapi>=0.139.0",
    "greenlet>=3.5.3",
    "openai-agents[any-llm,sqlalchemy]>=0.18.2",
    "pydantic-settings>=2.14.2",
    "scalar-fastapi>=1.8.2",
    "sqlmodel>=0.0.39",
    "uvicorn>=0.51.0",
    "yfinance>=1.5.1",
]
